myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path
from article import views
from comments.views import post_comment

urlpatterns = [
    path('admin', admin.site.urls),
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('article/<int:article_id>', views.article),
    path('comment', post_comment),
    path('editor/<int:article_id>', views.editor),
    path('newarticle', views.newarticle),
    path('login', views.login),
    path('logout', views.logout),
    path('example', views.example)
]

myblog/article/models.py
from django.db import models

# Create your models here.


class Tag(models.Model):
    tag = models.CharField(u'标签',max_length=256)

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = "标签"

class Article(models.Model):
    title = models.CharField(u'标题', max_length=256)
    content = models.TextField(u'内容')
    summary = models.TextField(u'摘要')
    tag = models.ManyToManyField(Tag, related_name='news_image')
    pub_date = models.DateTimeField(u'发表时间', auto_now_add=True, editable=True)

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return self.title

    class Meta:
        verbose_name = "文章"

myblog/comments/models.py
from django.db import models
from article.models import Article
# Create your models here.

class Comments(models.Model):
    name = models.CharField(max_length=100)
    #email = models.EmailField(max_length=255)
    #url = models.URLField(blank=True)
    text = models.TextField()

    created_time = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.text[:20]

myblog/comments/forms.py
from django import forms
from .models import Comments

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name', 'text']

myblog/article/views.py
from django.shortcuts import render, redirect
from .models import Article, Tag
from comments.models import Comments
from django.http import HttpResponse
# Create your views here.
from random import sample
import markdown
from django.template.loader import get_template 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from comments.views import CommentForm

from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required


def index(request):
    articles = Article.objects.all().order_by('-pub_date')
    hots = Article.objects.order_by('?')[:10]

    article_list = get_askpage_articles(articles, request.GET.get('page'))

    return render(request, 'index.html', locals())


def article(request, article_id):
    template = get_template('article.html')
    article = Article.objects.get(id=article_id) #查询指定类型的文章
    content = article.content

    hots = Article.objects.order_by('?')[:10]
    comments = Comments.objects.filter(article=article_id)

    html = template.render({
        'comments': comments,
        'hots': hots,
        'article': article,
        'form': CommentForm(),
        'content': markdown.markdown(
            content,
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
            ]
        ),

    })
    #previous_blog
    #last_blog
    return HttpResponse(html)

def search(request):
    keyword = request.GET.get('search') #获取搜索的关键词
    articles = Article.objects.filter(title__icontains=keyword)#获取到搜索关键词通过标题进行匹配
    #remen = Article.objects.filter(tui__id=2)[:6]
    #allcategory = Category.objects.all()
    #tags = Tag.objects.all()

    article_list = get_askpage_articles(articles, request.GET.get('page'))
    return render(request, 'search.html', locals())

def get_askpage_articles(articles, ask_page):
    paginator = Paginator(articles, 10)
    try:
        article_list = paginator.page(ask_page)
    except PageNotAnInteger:
        article_list = paginator.page(1)
    except EmptyPage:
        article_list = paginator.page(paginator.num_pages)

    return article_list

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        re = auth.authenticate(username=username, password=password)
        if re is not None:
            auth.login(request, re)
            return redirect('/')
        else:
            return render(request, 'login.html', {'login_error':'用户名或密码错误'})
    return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

@login_required
def editor(request, article_id):
    tags = Tag.objects.all()
    if article_id == 0:  # 新文章
        return render(request, 'editor.html', locals())
    else: # 修改已有文章
        article = Article.objects.filter(id=article_id)
        title = article[0].title
        content = article[0].content
        tag = article[0].tag
        return render(request, 'editor.html', locals())

@login_required
def newarticle(request):
    title = request.POST['title']
    content = request.POST['content']
    tags = request.POST['tags']
    article_id = request.POST['article_id']

    if int(article_id) > 0:
        article = Article.objects.filter(id=article_id)[0]
    else:    
        article = Article()
        
    article.title = title
    article.content = content
    article.save()

    
    tags = tags.strip().split()
    for tag in tags:
        tagobj, logic = Tag.objects.get_or_create(tag=tag)
        article.tag.add(tagobj)
    


    return HttpResponse('{"status": "success"}', content_type='application/json')

def example(request):
    return render(request, 'transindex.html')

myblog/comments/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

from django.utils.html import escape, strip_tags
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from article.models import Article

from .models import Comments
from .forms import CommentForm

def post_comment(request):
    if request.method == 'POST':
        article_id = request.POST.get('blog')
        article = get_object_or_404(Article, id=article_id)

        content = strip_tags(request.POST.get('text')).strip()
        name = strip_tags(request.POST.get('name')).strip()
        
        if name == "":
            name = "匿名网友"

        if content == "":
            return HttpResponse('{"status": "fail"}', content_type='application/json')
            
        comment = Comments()
        comment.name = name
        comment.text = content
        comment.article = article
        comment.save()

            #return HttpResponseRedirect("/index/")
        return HttpResponse('{"status": "success"}', content_type='application/json')
    return HttpResponse('{"status": "fail"}', content_type='application/json')

myblog/templates/article.html
{% extends 'base.html' %}

{% block content %}
    <span class="edit">编辑</span>
    <span class="article_id">{{ article.id }}</span>
    <h1>{{ article.title }}</h1>
    <div class="article">
        {{ content | safe }}
    </div>
    {% for comment in comments %}
    <hr>
    <div class="comment-display">
            <span class="name">网友：{{ comment.name }} </span><span>评论时间：{{ comment.created_time }}</span>
            <p class="content">评论内容：{{ comment.text }}</p>
    </div>
    {% endfor %}
    <hr>
    <section>
            <form class="comment-form" onsubmit="return false;">

                    <div class="row">
                        <div class="col-md-4">
                            <label for="{{ form.name.id_for_label }}">名字：</label>
                            {{ form.name }}
                        </div>
                        <div class="col-md-12">
                            <label for="{{ form.comment.id_for_label }}">评论：</label>
                            <textarea name="text" required="" id="id_text" placeholder="说点什么吧。。。"></textarea>
                            <button type="submit" class="comment-btn">发表</button>
                            <a id="successpost" style="display:none">发表成功！</a>
                        </div>
                    </div>    <!-- row -->
                    <input name="blog" type="hidden" id="js-name" value="{{ article.id }}">
            </form>
    </section>
{% endblock %}

myblog/templates/base.html
{% load static %}
<!doctype html>

<html lang="zh-cn">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'other/codestyle.css' %}">
    <link rel="stylesheet" href="{% static 'other/common.css' %}">
    <link rel="stylesheet" href="{% static 'other/list.css' %}">
    {% if article.title %}
    <title>{{article.title}}</title>
    {% else %}
    <title>Hello, world!</title>
    {% endif %}

  </head>

  <body>
    <div class="container">

        <div class="row  justify-content-center">
            <div class="col-sm-8 navbox">
                <ul class="nav">
                    <li class="nav-item"> <a class="nav-link active" href="#">首页</a> </li>
                    <li class="nav-item"> <a class="nav-link" href="#">原创文章</a> </li>
                    <li class="nav-item"> <a class="nav-link" href="#">转载文章</a> </li>
                    <li class="nav-item"> <a class="nav-link disabled" href="#">辐射4专题</a> </li>
                    </li>
                </ul>
                <ul class="nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="hello">hello,{{ user.username }}</span>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link exitlog" href="/logout">退出</a>
                        </li>
                    {% endif %}
                        <li class="nav-item"> <a class="nav-link newarticle" href="/editor/0">写新文章</a> </li>
                </ul>
            </div>
            <div class="col-sm-4">
                <form method="get" id="searchform" class="form-inline clearfix" action="{% url 'search' %}">
                <input class="form-control" name="search" id="s" placeholder="搜索关键词..." type="text">
                <button class="btn btn-green btn-small"><i class="fa fa-search"></i> 查找</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                {% block content %}
                {% endblock %}
            </div>

            <div class="col-sm-4">
                    <div class="information flex">     
                        <div class="touxiang"><img src="{% static 'other/hulitou.png' %}" style="border-radius:50%;">
                        </div>
                        <div class="touxiangright flex">
                            <div class="zuoyouming">莫逐有缘，勿住空忍。<br>一种平怀，泯然自尽。</div>
                            <div class="jumpout">
                                <div class="contactme">
                                    <span>联系我:</span>
                                    <a class="weixin" href="javascript:">
                                        <img class="qrcode wechatheight" src="{% static 'other/weixinerweima.jpeg' %}" alt="微信二维码">
                                        <img src="{% static 'other/weixin.jpeg' %}" alt="" class="weixinlogo">
                                    </a>
                                    <a class="qq" href="javascript:">
                                        <img class="qrcode qqheight" src="{% static 'other/QQerweima.jpeg' %}" alt="微信二维码">
                                        <img src="{% static 'other/qq.jpeg' %}" alt="" class="qqlogo">
                                    </a>
                                </div>
                            </div> 

                        </div>
                        
                    </div>

                    
                <hr>
            <div>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                              <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">最新文章</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">最新评论</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">浏览最多</a>
                            </li>
                          </ul>
                          <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <ul class="list-group">
                                {% for hot in hots %}
                                    <li style="color:black;">
                                        <a href="article/{{ hot.id }}" class="list-group-item clearfix" target="_blank">
                                            {{ hot.title }}
                                        </a>
                                    </li>
                                {% endfor %}
                                </ul>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
                            <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
                          </div>
            </div>



            </div>
        </div>
        <div class="row">

        </div>

            <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style ">
            <a class="addthis_button_preferred_1"></a>
            <a class="addthis_button_preferred_2"></a>
            <a class="addthis_button_preferred_3"></a>
            <a class="addthis_button_preferred_4"></a>
            <a class="addthis_button_compact"></a>
            <a class="addthis_counter addthis_bubble_style"></a>
        </div>
        <script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
        <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dbf68e662d4db6c"></script>
        <!-- AddThis Button END -->
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="{% static 'other/common.js' %}"></script>
    </body>
</html>

myblog/templates/editor.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8" />
        <title>Simple example - Editor.md examples</title>
        <link rel="stylesheet" href="{% static 'examples/css/style.css' %}" />
        <link rel="stylesheet" href="{% static 'css/editormd.css' %}" />
        <link rel="stylesheet" href="{% static 'other/editor.css' %}" />
        <link rel="shortcut icon" href="https://pandao.github.io/editor.md/favicon.ico" type="image/x-icon" />
    </head>
    <body>
        <div id="layout">
            <header class="flex">
                <div id="titlebox" style="width:100%">
                    <input id="title" maxlength="100" placeholder="输入文章标题" value="{{ title }}">
                </div>
                <div class="article_type">
                    <div>
                        <label>文章类型:</label>
                    </div>
                    <div class="type_box">
                            <select class="textfield" id="types">
                                <option value="0" selected="selected">请选择</option> 
                                <option value="original">原创</option> 
                                <option value="repost">转载</option> 
                                <option value="translated">翻译</option>
                            </select>
                    </div>
                </div>
                <div class="flex"><button class="but">发布文章</button></div>
            </header>
            <span class="article_id">{{ article_id }}</span>
            <div class="tags flex">
                <label>文章标签:</label>
                <input names="tags" type="text" id="tags-input" value="{{ tag }}">
                <dl class="common-tags flex">
                    <dt>常用标签:</dt>
                    <dd class="flex">
                        {% for tag in tags %}
                        <span class="single-tag">{{ tag.tag }}</span>
                        {% endfor %}
                    </dd>
                </dl>
            </div>
            <div id="test-editormd">
                <textarea id="content" style="display:none;">{{ content }}</textarea>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="{% static 'editormd.min.js' %}"></script>
        <script src="{% static 'other/common.js' %}"></script>
        <script type="text/javascript">
			var testEditor;

            $(function() {
                testEditor = editormd("test-editormd", {
                    width   : "90%",
                    height  : 640,
                    syncScrolling : "single",
                    path    : "/static/lib/"
                });
                
                /*
                // or
                testEditor = editormd({
                    id      : "test-editormd",
                    width   : "90%",
                    height  : 640,
                    path    : "../lib/"
                });
                */
            });
        </script>
    </body>
</html>

myblog/templates/index.html
{% extends 'base.html' %}

{% block content %}
    {% include 'list.html' %}
{% endblock %}

myblog/templates/list.html
{% for article in article_list %}
<div class="alert alert-{% cycle 'primary' 'success' 'danger' %}" role="alert">
    <h4>
        <a href="/article/{{ article.id }}" target="_blank" title="{{ article.title }}">
        {{ article.title }}
        </a>
    </h4>
    <hr>
    <p class="summary">
        {{ article.summary }}
    </p>

    <div class="meta flex">
        <div>
            <span>标签：</span>
            {% for tag in article.tag.all %}
                <span>{{ tag }}</span>
            {% endfor %}
        </div>

        <time>{{ article.pub_date }}</time>
    </div>

</div>
{% endfor %}

<div class="pagination">
    <ul>
        {% if article_list.has_previous %}
        <li class="prev-page"><a href="?page={{ article_list.previous_page_number }}" target="_blank">上一页</a></li>
        {% else %}
         <li class="prev-page"></li>
        {% endif %}


        {% for num in article_list.paginator.page_range %}
            {% if num %}
                {% ifequal num article_list.number %}
                    <li class="active"><span>{{ num }}</span></li>
                {% else %}
                    <li><a href="?page={{ num }}">{{ num }}</a></li>
                {% endifequal %}
            {% else %}
                <li class="disabled"><span>...</span></li>
            {% endif %}
        {% endfor %}


        {% if article_list.has_next %}
            <li class="next-page"><a href="?page={{ article_list.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="prev-page"></li>
        {% endif %}
    </ul>
</div>

myblog/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body{
            display: flex;
            justify-content: center;
            align-items: space-around;
        }
    </style>
</head>
<body>
    <div>
        <form action="/login" method="POST">
            <h2>Please sign in </h2>
            <input type="text" name="username" />
            <input type="password" name="password" />
            <button type="submit">Sign in </button>
            <p style="color: red">{{ login_error }}</p>
        </form>
</div>
</body>
</html>

myblog/templates/search.html
{% extends 'base.html' %}

{% block content %}
    <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url 'index' %}">首页</a> » 
    <span class="current">关键词：{{ ss }}</span></div>
    {% include 'list.html' %}
{% endblock %}